spring:
  application:
    name: course-catalog-service
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5438/courses
    username: postgres
    password: postgres
  jpa:
    generate-ddl: true
    show-sql: true
message: Hello from default profile

---

spring:
  config:
    activate:
      on-profile: prod
message: Hello from prod profile
